# Generated by Django 5.2.4 on 2025-08-06 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='category',
        ),
        migrations.RenameField(
            model_name='expenseitem',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='onlinepayment',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='onlinepayment',
            old_name='bill_number',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='bill_image',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='n9huY74m', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('online', 'Online'), ('local', 'Local')], max_length=10)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='expenseapp.shop')),
            ],
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenseapp.distributor'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenseapp.distributor'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
