# Generated by Django 5.2.4 on 2025-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_alter_shop_shop_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='6vPzyNKC', max_length=10, unique=True),
        ),
    ]
