# Generated by Django 5.2.4 on 2025-07-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_remove_category_category_type_alter_shop_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenseapp.category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='hz67VXVD', max_length=10, unique=True),
        ),
    ]
