# Generated by Django 5.2.4 on 2025-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_customuser_approval_status_alter_shop_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='GfwRAbvU', max_length=10, unique=True),
        ),
    ]
