# Generated by Django 5.2.4 on 2025-08-09 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0005_expenseitem_is_verified_expenseitem_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_online_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='1YbfmmyW', max_length=10, unique=True),
        ),
    ]
