# Generated by Django 5.2.4 on 2025-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0006_onlinepayment_paid_at_onlinepayment_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='bf6YggBo', max_length=10, unique=True),
        ),
    ]
