# Generated by Django 5.2.4 on 2025-07-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0007_alter_shop_shop_code_salaryexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='qCAvDYvy', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='bill_images/')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.category')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='expenseapp.expense')),
            ],
        ),
    ]
