# Generated by Django 5.2.4 on 2025-07-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0008_alter_shop_shop_code_onlinepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='PEF9caNe', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='DailySaleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_in_account', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_benefit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cumulative_monthly_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.shop')),
            ],
            options={
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
