# Generated by Django 5.1.4 on 2025-08-11 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0008_alter_shop_shop_code_supervisorshopaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='mXHvM2Ww', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='supervisorshopaccess',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_accesses', to='expenseapp.shop'),
        ),
        migrations.AlterField(
            model_name='supervisorshopaccess',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
