# Generated by Django 5.1.4 on 2025-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_alter_shop_shop_code_alter_supervisorshopaccess_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='WgPc0wv8', max_length=10, unique=True),
        ),
    ]
