# Generated by Django 5.1.4 on 2025-08-22 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0010_alter_shop_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('staff', 'Staff'), ('partner', 'Partner')], default='staff', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='aVmDoh4H', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PartnerShopAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partner_accesses', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_accesses', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_accesses', to='expenseapp.shop')),
            ],
            options={
                'verbose_name_plural': 'Partner Shop Accesses',
                'unique_together': {('partner', 'shop')},
            },
        ),
    ]
